### ISSUE TITLE
dev goes out of bounds on devices

### ISSUE THREAD

**Issue by PhilipNelson5** [ksundberg/CourseMaterials#12]
In Simulation.cpp this line appears twice: ``auto dev = jobs[job].tasks[jobs[job].cur].device;`` followed by some form of ``devices[dev]``. When stepping though however, ``dev`` is sometimes outside the bounds of ``devices``. 
~~~~
Job: 3 dev: 2 size: 2
Job: 3 dev: 2 size: 2
Job: 4 dev: 2 size: 2
Job: 6 dev: 2 size: 2
Job: 3 dev: 2 size: 2
Job: 3 dev: 2 size: 2
Job: 4 dev: 2 size: 2
Job: 1 dev: 2 size: 2
Job: 9 dev: 2 size: 2
Job: 9 dev: 2 size: 2
~~~~

**Comment by johnsonjo4531** [comment]
This out of bounds dev and devices appears to be in my stack trace for a segmantation fault error in the fiforeadyqueue::next method. So I can confirm its happening.

**Comment by PhilipNelson5** [comment]
fix:
Task.cpp : 10
`std::uniform_int_distribution<> dist(low, high - 1);`
Task.cpp : 37
`auto max = type == cs3100::Task::Type::CPU ? maxPage : maxDevice - 1;`

**Comment by AmmonHepworth** [comment]
In my program your second fix does the trick but implementing the first fix in any combination causes seg faults in all cases. Can anybody else confirm?

**Comment by PhilipNelson5** [comment]
I changed it, only the one from line 37 is needed
